# Site settings
title: Reason About
email: info@reasonabout.co
description: A blog that brings fresh insights from a bunch of curious web devs together in one space.
url: http://reasonabout.co
twitter_username: reasonabout_co
sidebar_image: assets/cover.jpg
