# Site settings
title: Reason About
email: info@reasonabout.co
description: Fresh insights and information from a group of full stack students (and their instructors)
url: http://reasonabout.co
twitter_username: reasonabout_co
sidebar_image: assets/main/cover.jpg
